# Generated by Django 4.1.7 on 2023-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_link',
            field=models.URLField(verbose_name='Оригинальная ссылка'),
        ),
    ]
